### ISSUE TITLE
Preview not working on Sublime Text 3 for Windows

### ISSUE THREAD

**Issue by ryanewtaylor** [munro/SublimeGraphvizPreview#1]
Does this work in Sublime Text 3 for Windows? I am unable to generate a preview of the diagram with Sublime Text 3 on Windows.

**Comment by courier10px** [comment]
For the time being the [rlodbrok fork](https://github.com/rlodbrok/SublimeGraphvizPrev) could be used on windows. I wrote a small post with installation instructions [here](http://blog.courier10pt.com/getting-sublimetext-graphvizpreview-to-work-on-windows/)

**Comment by munro** [comment]
Hey thanks for all the hard work, it's pretty time consuming for me to test all the platforms, so if people are finding the fork works well on Windows I can just merge it it!

**Comment by courier10px** [comment]
Good to hear :-)

Have a nice day

**Comment by rlodbrok** [comment]
This is now resolved if graphviz is pre-installed and in the environment PATH.

**Comment by munro** [comment]
@rlodbrok hey man thanks a lot!  :+1: :octocat: :rocket: :beers:

**Comment by AndersDeleuran** [comment]
Thanks guys, loving this!
